version: '3'
services:
  client:
    tty: true
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    volumes:
      - ./client:/var/www
    ports:
      - 3000:3000
    networks:
      - lesson

  go:
    image: golang:1.20-alpine
    tty: true
    volumes:
      - ./go:/go
      - ./go/src:/go/src
    ports:
      - "8080:8080"
    working_dir: /go/src/app
    networks:
      - lesson

  dev-postgres:
    image: postgres:15.1-alpine
    tty: true
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: udemy
      POSTGRES_PASSWORD: udemy
      POSTGRES_DB: udemy
    networks:
      - lesson

  pgadmin:
    image: dpage/pgadmin4:latest
    tty: true
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - lesson

networks:
  lesson:
